### ISSUE TITLE
Latest blog autoposted multiple times

### ISSUE THREAD

**Issue by vexillia** [woodruffw/autopost#39]
Everytime I use this command:

autopost --config-file "/home/vexillia/.autopost.toml" atom https://blog.vexillia.me.uk/feeds/posts/default

I get multiple copies of the latest blog post.  I expected subsequent runs not to post it.

**Comment by woodruffw** [comment]
That's by design -- `autopost` is entirely stateless. If you want to avoid posting the same thing multiple times, you need to ensure that `autopost` only runs after a new post becomes live.

Personally, I do that in CI/CD by getting the previous post's title, and then only running `autopost` if the deployment causes a title change.

Here's a rough excerpt of my CI/CD flow:

```yaml
  pre-deploy:
    runs-on: ubuntu-latest
    outputs:
      title: ${{ steps.latest-blog-title.outputs.title }}
    steps:
      - name: dependencies
        run: |
          sudo apt-get install -y jq
          # this installs xq as well, which is what we'll use
          python -m pip install yq


      - name: get the most recent blog post title
        id: latest-blog-title
        run: |
          title=$(curl https://blog.yossarian.net/feed.xml | \
            xq -r '.feed.entry[0].title."#text"')


          echo "title=${title}" | tee -a "${GITHUB_OUTPUT}"

  deploy: ... # your own deployment here

  autopost:
    # GitHub Actions can't see transitive `needs` when grabbing job outputs?
    needs: [pre-deploy, deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ">= 3.11"

      - name: dependencies
        run: |
          sudo apt-get install -y jq
          # this installs xq as well, which is what we'll use
          python -m pip install yq autopost

      - name: check for a new post
        env:
          LAST_POST_TITLE: ${{ needs.pre-deploy.outputs.title }}
        run: |
          latest_title=$(curl https://blog.yossarian.net/feed.xml | \
            xq -r '.feed.entry[0].title."#text"')

          if [[ "${latest_title}" = "${LAST_POST_TITLE}" && "${{ github.event.inputs.force-autopost }}" != "true" ]]; then
            echo "no new post, not autoposting"
            exit 0
          fi

          echo "autoposting for: ${latest_title}"
          autopost --verbose atom https://blog.yossarian.net/feed.xml
 ```
